### PR TITLE
Test pull request that squashes multiple commits into one

### PR DESCRIPTION
**Pull request by anders-schneider**
Will squash 3 commits into 1.

### CODE REVIEW

**Comment by anders-schneider** [comment]
Closing because I couldn't find a way to squash the commits - maybe I have to do that earlier in the process?

**Comment by anders-schneider** [comment]
Oh actually it looks like you have the option to squash commits when merging an approved pull request (https://www.git-tower.com/learn/git/faq/git-squash/)

**Review by willrlin — APPROVED** [review]

**Comment by willrlin** [comment]
I wonder if there's a way to link an issue to this pull request without closing the issue?

**Comment by willrlin** [comment]
Could you try making your commit message have #3 in it? I think that should link without closing once you submit this.

**Comment by anders-schneider** [comment]
Yeah I'll try that!

Also, note to self: now that this PR is approved, the "Merge pull request" button has a little dropdown on the side with the option to "Squash and merge". Trying that now...

**Pull request merged**
